# netlify.toml

# Basic build settings
[build]
  functions = "netlify/functions" # Specifies the directory for Netlify Functions
  publish = "."                   # Sets the root directory as the publish directory for the site

# Functions settings
# Temporarily emptying this block to see if it resolves the parsing error.
# Netlify will use its default Node.js version and bundler.
[functions]
  # node_version = "18"           # Temporarily removed due to parsing error
  # node_bundler = "esbuild"      # Temporarily removed

# Redirect rules for Single Page Application (SPA) behavior and clean URLs.
[[redirects]]
  from = "/admin/*"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/cart/*"
  to = "/cart.html"
  status = 200

[[redirects]]
  from = "/product-details/*"
  to = "/product-details.html"
  status = 200

# Catch-all redirect for Single Page Application (SPA) routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
