# netlify.toml

# Basic build settings
[build]
  functions = "netlify/functions" # Specifies the directory for Netlify Functions
  publish = "."                   # Sets the root directory as the publish directory for the site

# Functions settings
# This block is intentionally sparse to avoid the "node_version must be an object" parsing error.
# Netlify will use its default Node.js version and bundler.
# We can try re-adding specific versions/bundlers later if this deploys successfully.
[functions]
  # node_version = "18"      # KEEP THIS COMMENTED OUT or REMOVED for now
  # node_bundler = "esbuild" # KEEP THIS COMMENTED OUT or REMOVED for now

# Redirect rules for Single Page Application (SPA) behavior and clean URLs.
[[redirects]]
  from = "/admin/*"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/cart/*"
  to = "/cart.html"
  status = 200

[[redirects]]
  from = "/product-details/*"
  to = "/product-details.html"
  status = 200

# Catch-all redirect for Single Page Application (SPA) routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
