# netlify.toml

# Basic build settings
[build]
  functions = "netlify/functions" # Specifies the directory for Netlify Functions
  publish = "."                   # Sets the root directory as the publish directory for the site

# Functions settings
# Re-introducing node_version as the previous parsing error was likely due to other lines.
[functions]
  node_version = "18"             # Specifies Node.js version 18 for the function runtime environment
  # node_bundler = "esbuild"      # Keep this commented out for now, can re-add if build is stable

# Redirect rules for Single Page Application (SPA) behavior and clean URLs.
[[redirects]]
  from = "/admin/*"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/cart/*"
  to = "/cart.html"
  status = 200

[[redirects]]
  from = "/product-details/*"
  to = "/product-details.html"
  status = 200

# Catch-all redirect for Single Page Application (SPA) routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
