# netlify.toml (Minimal Test Version)

# Basic build settings
[build]
  functions = "netlify/functions" # Specifies the directory for Netlify Functions
  publish = "."                   # Sets the root directory as the publish directory for the site

# ALL REDIRECTS TEMPORARILY REMOVED FOR PARSING TEST
# We will add them back once the core parsing issue is resolved.

# Catch-all redirect for Single Page Application (SPA) routing.
# This is the most essential redirect for many SPA frameworks.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
